version: '3'
services:

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - 127.0.0.1:27017:27017
    environment:
        MONGO_INITDB_DATABASE: db
    expose:
      - 27017
    networks:
      - omniboard
    volumes:
      - ./db:/data/db

  mongo-express:
    image: mongo-express
    depends_on: 
      - mongo
    ports:
      - 127.0.0.1:8081:8081
    networks:
      - omniboard

  omniboard:
    image: vivekratnavel/omniboard:latest
    command: ["-m", "mongo:27017:db"]
    ports:
      - 127.0.0.1:9000:9000
    depends_on:
      - mongo
    networks:
      - omniboard

networks:
  omniboard:
